apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: roboshop
  name: roboshop-trainee
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"] # nouns
  verbs: ["get", "watch", "list"] # actions
---
apiVersion: rbac.authorization.k8s.io/v1
# This cluster role binding allows anyone in the "manager" group to read secrets in any namespace.
kind: RoleBinding
metadata:
  name: roboshop-trainee
  namespace: roboshop
subjects:
- kind: User
  name: venu # Name is case sensitive
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: roboshop-trainee
  apiGroup: rbac.authorization.k8s.io